import { Table, Reservation, CashierMetrics } from "@/types/cashier";

export const mockReservations: Reservation[] = [
  {
    id: 1,
    tableId: 4,
    clientName: "María González",
    phone: "+54 9 11 4523-8871",
    time: "13:00",
    persons: 4,
    note: "Festejo de aniversario",
  },
  {
    id: 2,
    tableId: 7,
    clientName: "Carlos Fernández",
    phone: "+54 9 11 6234-1190",
    time: "13:30",
    persons: 2,
  },
  {
    id: 3,
    tableId: 11,
    clientName: "Lucía Martínez",
    phone: "+54 9 11 5567-9923",
    time: "14:00",
    persons: 6,
    note: "Cumpleaños - necesitan silla para bebé",
  },
  {
    id: 4,
    tableId: 12,
    clientName: "Andrés Pérez",
    phone: "+54 9 11 7890-4432",
    time: "20:00",
    persons: 10,
  },
  {
    id: 5,
    tableId: 9,
    clientName: "Sofía Romero",
    phone: "+54 9 11 3345-6678",
    time: "21:00",
    persons: 2,
  },
  {
    id: 6,
    tableId: 6,
    clientName: "Diego Torres",
    phone: "+54 9 11 9981-2234",
    time: "13:00",
    persons: 2,
  },
];

export const mockTables: Table[] = [
  // SALÓN
  {
    id: 1,
    zone: "salon",
    status: "libre",
    persons: 2,
    lastPaidOrder: {
      id: "0040",
      tableId: 1,
      status: "pagado",
      items: [],
      subtotal: 15400,
      iva: 2310,
      total: 17710,
      createdAt: "11:30 a.m.",
    },
  },
  {
    id: 2,
    zone: "salon",
    status: "ocupada",
    persons: 4,
    currentOrder: {
      id: "0038",
      tableId: 2,
      status: "servido",
      items: [
        { quantity: 2, name: "Lomo completo", price: 17000 },
        { quantity: 3, name: "Cerveza artesanal", price: 6300 },
        { quantity: 2, name: "Flan con dulce de leche", price: 3600 },
      ],
      subtotal: 27700,
      iva: 4155,
      total: 31855,
      createdAt: "11:45 a.m.",
    },
  },
  {
    id: 3,
    zone: "salon",
    status: "ocupada",
    persons: 4,
    currentOrder: {
      id: "0041",
      tableId: 3,
      status: "servido",
      items: [
        { quantity: 2, name: "Milanesa napolitana", price: 8500 },
        { quantity: 1, name: "Ensalada mixta", price: 3200 },
      ],
      subtotal: 15300,
      iva: 2295,
      total: 17595,
      createdAt: "12:00 p.m.",
    },
  },
  {
    id: 4,
    zone: "salon",
    status: "reservada",
    persons: 4,
    reservation: mockReservations[0],
  },
  {
    id: 5,
    zone: "salon",
    status: "ocupada",
    persons: 2,
    currentOrder: {
      id: "0042",
      tableId: 5,
      status: "servido",
      items: [
        { quantity: 1, name: "Bife de chorizo", price: 7200 },
        { quantity: 1, name: "Ensalada mixta", price: 2100 },
        { quantity: 2, name: "Vino tinto copa", price: 3000 },
      ],
      subtotal: 12300,
      iva: 1845,
      total: 14145,
      createdAt: "12:30 p.m.",
    },
  },
  // TERRAZA
  {
    id: 6,
    zone: "terraza",
    status: "ocupada",
    persons: 2,
    currentOrder: {
      id: "0043",
      tableId: 6,
      status: "pendiente",
      items: [
        { quantity: 1, name: "Pizza mozzarella", price: 5500 },
        { quantity: 1, name: "Empanadas x6", price: 3200 },
        { quantity: 2, name: "Agua con gas", price: 1200 },
      ],
      subtotal: 11115,
      iva: 1668,
      total: 13110,
      createdAt: "12:45 p.m.",
    },
  },
  {
    id: 7,
    zone: "terraza",
    status: "reservada",
    persons: 2,
    reservation: mockReservations[1],
  },
  {
    id: 8,
    zone: "terraza",
    status: "ocupada",
    persons: 6,
    currentOrder: {
      id: "0045",
      tableId: 8,
      status: "pendiente",
      items: [
        { quantity: 2, name: "Sorrentinos de ricota", price: 10200 },
        { quantity: 1, name: "Pan de ajo", price: 1200 },
      ],
      subtotal: 11400,
      iva: 1710,
      total: 11615,
      createdAt: "01:10 p.m.",
    },
  },
  {
    id: 9,
    zone: "terraza",
    status: "reservada",
    persons: 2,
    reservation: mockReservations[4],
  },
  // PRIVADO
  {
    id: 10,
    zone: "privado",
    status: "ocupada",
    persons: 6,
    currentOrder: {
      id: "0044",
      tableId: 10,
      status: "preparacion",
      items: [
        { quantity: 3, name: "Ravioles al pesto", price: 14400 },
        { quantity: 2, name: "Tiramisú", price: 5000 },
        { quantity: 2, name: "Espumante copa", price: 4400 },
      ],
      subtotal: 23000,
      iva: 3450,
      total: 26450,
      createdAt: "01:00 p.m.",
      note: "Cumpleaños - traer postre con velita",
    },
  },
  {
    id: 11,
    zone: "privado",
    status: "reservada",
    persons: 8,
    reservation: mockReservations[2],
  },
  {
    id: 12,
    zone: "privado",
    status: "reservada",
    persons: 10,
    reservation: mockReservations[3],
  },
];

export const mockMetrics: CashierMetrics = {
  activeOrders: 6,
  ordersInPreparation: 2,
  occupiedTables: 6,
  totalTables: 12,
  reservedTables: 5,
  reservationsToday: mockReservations.length,
};